SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

CREATE TABLE `attempts` (
  `ID_T` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_ROUND` bigint(20) UNSIGNED NOT NULL,
  `GUESS` varchar(255) NOT NULL,
  `IS_CORRECT` tinyint(1) DEFAULT 0,
  PRIMARY KEY (`ID_T`),
  KEY `ID_ROUND` (`ID_ROUND`),
  CONSTRAINT `fk_attempts_round` FOREIGN KEY (`ID_ROUND`) REFERENCES `rounds` (`ID_ROUND`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `friends` (
  `ID_U` int(11) NOT NULL,
  `ID_A` int(11) NOT NULL,
  PRIMARY KEY (`ID_U`, `ID_A`),
  CONSTRAINT `fk_friends_u` FOREIGN KEY (`ID_U`) REFERENCES `users` (`ID_U`) ON DELETE CASCADE,
  CONSTRAINT `fk_friends_a` FOREIGN KEY (`ID_A`) REFERENCES `users` (`ID_U`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `friend_requests` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sender_id` int(11) NOT NULL,
  `receiver_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_friend_requests_sender` FOREIGN KEY (`sender_id`) REFERENCES `users` (`ID_U`) ON DELETE CASCADE,
  CONSTRAINT `fk_friend_requests_receiver` FOREIGN KEY (`receiver_id`) REFERENCES `users` (`ID_U`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `played` (
  `ID_PLAYED` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_U` bigint(20) UNSIGNED NOT NULL,
  `ID_R` bigint(20) UNSIGNED NOT NULL,
  `SCORE` int(11) DEFAULT 0,
  `IS_THE_CHALLENGER` tinyint(1) DEFAULT 0,
  PRIMARY KEY (`ID_PLAYED`),
  KEY `ID_U` (`ID_U`),
  KEY `ID_R` (`ID_R`),
  CONSTRAINT `fk_played_user` FOREIGN KEY (`ID_U`) REFERENCES `users` (`ID_U`) ON DELETE CASCADE,
  CONSTRAINT `fk_played_room` FOREIGN KEY (`ID_R`) REFERENCES `rooms` (`ID_R`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `ranking` (
  `ID_U` bigint(20) UNSIGNED NOT NULL,
  `POSITION` int(11) DEFAULT NULL,
  `AMOUNT_OF_WINS` int(11) DEFAULT 0,
  `NUMBER_OF_GAMES` int(11) DEFAULT 0,
  `POINT_AMOUNT` int(11) DEFAULT 0,
  PRIMARY KEY (`ID_U`),
  CONSTRAINT `fk_ranking_u` FOREIGN KEY (`ID_U`) REFERENCES `users` (`ID_U`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `rooms` (
  `ID_R` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ROOM_NAME` varchar(100) NOT NULL,
  `ID_O` bigint(20) UNSIGNED NOT NULL,
  `PRIVATE` tinyint(1) DEFAULT 0,
  `PASSWORD` varchar(50) DEFAULT NULL,
  `PLAYER_CAPACITY` int(11) DEFAULT 10,
  `TIME_LIMIT` int(11) DEFAULT 5,
  `POINTS` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_R`),
  KEY `ID_O` (`ID_O`),
  CONSTRAINT `fk_rooms_owner` FOREIGN KEY (`ID_O`) REFERENCES `users` (`ID_U`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `rounds` (
  `ID_ROUND` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_R` bigint(20) UNSIGNED NOT NULL,
  `PLAYER_OF_THE_TIME` bigint(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`ID_ROUND`),
  KEY `ID_R` (`ID_R`),
  KEY `PLAYER_OF_THE_TIME` (`PLAYER_OF_THE_TIME`),
  CONSTRAINT `fk_rounds_room` FOREIGN KEY (`ID_R`) REFERENCES `rooms` (`ID_R`) ON DELETE CASCADE,
  CONSTRAINT `fk_rounds_player` FOREIGN KEY (`PLAYER_OF_THE_TIME`) REFERENCES `users` (`ID_U`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `users` (
  `ID_U` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `NICKNAME` varchar(50) NOT NULL,
  `EMAIL` varchar(100) DEFAULT NULL UNIQUE,
  `PASSWORD` varchar(255) DEFAULT NULL,
  `ONLINE` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID_U`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;